### ISSUE TITLE
Convert CSS to SCSS

### ISSUE THREAD

**Issue by txwkx** [txwkx/RDFJS4U#1]

**Comment by txwkx** [comment]
Preferably **SCSS**.
- [ ] modify the current css
- [ ] eliminate the usage of `!important` 

(webpack module loader and packages are already installed)

**Comment by danhannigan** [comment]
I'd be happy to take this on :)

**Comment by txwkx** [comment]
Hey, @danhannigan, you got it ! 

I like the separation option

Cheers :beers:

**Comment by danhannigan** [comment]
Hey @txwkx - got started on this, then I realized web-pack and I aren't the best of friends (I'm still goofing around with grunt/gulp for my compiling needs) 

How do you want to go about compiling this?

**Comment by txwkx** [comment]
Yo, @danhannigan I found this [webpack-css-example repo](https://github.com/bensmithett/webpack-css-example). 

I may try n tweak the current config during the weekend to eliminate any webpack related work for you

**Comment by danhannigan** [comment]
Hey @txwkx - just checking in. I've made some good progress, going to pass my scss files through a compiler and test them just to make sure they're working. I'll be addressing the !important issues today/tonight too.

**Comment by txwkx** [comment]
@danhannigan Apparently removing line 224 in __style.css__ `border: 1px solid transparent;` helps.

Hope I'll not be overriding bootstrap styles like on this project in the nearest feature :pray:

**Comment by danhannigan** [comment]
Yep, that'll do it. `.nav-tabs li` has greater specificity than a class of just `.red` - so  '.nav-tabs li' properties were taking priority (sorry if you're familiar with CSS and get that already and I'm just being an over-explaining jerk :D )
